load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "spring_market",
    hdrs = [
        "market_event.hpp",
        "synthetic_market_data_source.hpp",
        "synthetic_market_data_runtime.hpp",
    ],
    deps = [
        "//common:common",
        "//logging:logging",
        "//spring/logging:spring_logging",
    ],
    visibility = ["//visibility:public"],
)